Initial commit for Retry module
tech-salad/resilience pull request #1
Opened 2022-05-18 10:20 UTC by MVenglarcik

2022-05-30 15:09 UTC, typekpb requested changes
any chance to use all lowercase? => `Retry` -> `retry`

2022-05-30 15:09 UTC, typekpb commented on Retry/HELP.md
> +# Getting Started
convention says, file should be named README.md, to be able to show it directly in the Github UI once opening the folder

2022-05-30 15:09 UTC, typekpb commented on Retry/src/main/java/org/techsalad/retry/controller/SaladsController.java
> +    log.log(INFO, "Bola by Kucapaca, ale skúsim zopakovať po {0}-krát!",
please use the english language only + log messages that are technically exact

2022-05-30 15:09 UTC, typekpb commented on Retry/src/main/java/org/techsalad/retry/controller/SaladsController.java
> +    log.log(INFO, "Všetko dobre dopadlo po {0}-pokusoch :)", event.getNumberOfRetryAttempts());
dtto

2022-05-30 15:09 UTC, typekpb commented on Retry/src/main/java/org/techsalad/retry/controller/SaladsController.java
> +    log.log(WARNING, "Dačo hrozné! Urobilo bác po {0}-pokusoch! :(",
dtto

2022-05-30 15:09 UTC, typekpb commented on Retry/src/main/java/org/techsalad/retry/service/SaladsService.java
> +      throw new IllegalStateException("Bola kucapaca! Neviem najsť ani jeden šalát. :(");
dto

2022-05-30 15:09 UTC, typekpb commented on Retry/src/main/java/org/techsalad/retry/service/SaladsService.java
> +    return Collections.singletonList("Najsamlepší šalátik!");
dtto

2022-05-30 15:09 UTC, typekpb commented on Retry/src/test/java/org/techsalad/retry/controller/SaladsControllerTest.java
> +    assertThrows(RuntimeException.class, getSalads, "Hmm... tu to malo spadnut!??");
dtto

2022-05-30 15:09 UTC, typekpb commented on Retry/src/test/java/org/techsalad/retry/controller/SaladsControllerTest.java
> +  private static final RuntimeException RUNTIME_EXCEPTION = new RuntimeException("Zle, nedobre!");
dtto

2022-05-30 15:09 UTC, typekpb commented on Retry/src/main/java/org/techsalad/retry/service/SaladsService.java
> +  private int failuresCount = 0;
as a bonus/optional step, we might want to refactor the sample in a way, that failing service would be part of unit test only.

as this means, we'll have to redeploy to demo again to simulate the failure.

potentially we should just call some external URL in the source code, that would be mocked for the test/demo purposes. Wiremock might be an option: https://wiremock.org/docs/stateful-behaviour/

2022-05-31 13:49 UTC, MVenglarcik commented on Retry/src/main/java/org/techsalad/retry/service/SaladsService.java
> +  private int failuresCount = 0;
Ignored as jUnit tests covers also failure case + this is used for demonstrating the retry mechanism.

2022-05-31 13:51 UTC, typekpb approved these changes

2022-05-31 13:57 UTC, merged